/**
 * tests/roof-3d-2026-10-02.test.js — the code-correct roof section on
 * /services/roof-replacement: the static gable cutaway (SVG, generated by
 * scripts/build-roof-diagram.js) and the tap-to-load 3D view
 * (docs/assets/js/roof-3d.js + the trimmed, vendored Three.js).
 *
 * Run: node tests/roof-3d-2026-10-02.test.js
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');
const ROOT = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');

let passed = 0, failed = 0; const fails = [];
function ok(name, cond, detail) {
  if (cond) { passed++; console.log('  ✓ ' + name); }
  else { failed++; fails.push(name); console.log('  ✗ ' + name + (detail ? '\n      ' + detail : '')); }
}

const KEYS = ['deck', 'drip', 'ice', 'under', 'starter', 'shingles', 'boot', 'flash', 'ridge', 'soffit'];

(async () => {
  console.log('\n1. The page');
  const page = read('docs/services/roof-replacement.html');
  ok('section present with the static diagram as the first thing shown', /id="code-correct-roof"/.test(page) && /<img class="roof3d-svg" src="\/assets\/images\/roof-layers\.svg"/.test(page));
  ok('the diagram has real alt text naming the code items', /alt="A gable roof cut away layer by layer: roof deck, drip edge/.test(page));
  const legend = [...page.matchAll(/data-roof3d-item="([a-z]+)"/g)].map((m) => m[1]);
  ok('legend lists all 10 items in order', legend.join() === KEYS.join(), legend.join());
  ok('code items are tagged CODE in the legend (7 of 10)', (page.match(/<li data-roof3d-item="[a-z]+"><span class="roof3d-n">\d+<\/span><span class="roof3d-t"><span class="roof3d-code">CODE<\/span>/g) || []).length === 7);
  ok('kick-out flashing is named (code, not drawn)', /kick-out flashing wherever a roof edge runs into a wall/.test(page));
  ok('3D is opt-in: a "See it in 3D" button, module script, external CSS', /data-roof3d-start>See it in 3D</.test(page) && /<script type="module" src="\/assets\/js\/roof-3d\.js"><\/script>/.test(page) && /href="\/assets\/css\/roof-3d\.css"/.test(page));
  ok('no inline handlers on the section', !/\son[a-z]+=/.test(page.slice(page.indexOf('id="code-correct-roof"'), page.indexOf('STRAIGHT FROM THE MANUFACTURER'))));

  console.log('\n2. The static diagram');
  const svg = read('docs/assets/images/roof-layers.svg');
  ok('accessible SVG (role img, title, desc)', /role="img"/.test(svg) && /<title id="t">/.test(svg) && /<desc id="d">/.test(svg));
  ok('10 numbered callouts', [...svg.matchAll(/class="num">(\d+)</g)].map((m) => +m[1]).sort((a, b) => a - b).join() === '1,2,3,4,5,6,7,8,9,10');
  ok('7 CODE tags on callouts + 1 in the key', (svg.match(/class="code">CODE</g) || []).length === 8);
  ok('motion respects prefers-reduced-motion', /@media \(prefers-reduced-motion: reduce\)/.test(svg));
  ok('no script in the SVG', !/<script/i.test(svg));
  const before = svg;
  require('child_process').execFileSync(process.execPath, [path.join(ROOT, 'scripts', 'build-roof-diagram.js'), path.join(require('os').tmpdir(), 'roof-layers-check.svg')]);
  ok('the committed SVG is exactly what the generator writes (edit the script, not the SVG)', fs.readFileSync(path.join(require('os').tmpdir(), 'roof-layers-check.svg'), 'utf8') === before);

  console.log('\n3. The 3D view');
  const js = read('docs/assets/js/roof-3d.js');
  ok('Three.js loads only inside mountRoof3d (tap-to-load), never at module top level', !/^import /m.test(js) && /await import\('\.\/vendor\/three-roof\.min\.js'\)/.test(js));
  ok('every legend key has a 3D anchor and an item', KEYS.every((k) => new RegExp("key: '" + k + "'").test(js) && new RegExp('\\b' + k + ': \\(\\) =>').test(js)));
  ok('wheel is never captured; vertical swipes still scroll', !/addEventListener\('wheel'/.test(js) && /touchAction = 'pan-y'/.test(js));
  ok('reduced motion: no auto-spin', /if \(!reduce && !spun\)/.test(js));
  ok('no WebGL → the button hides and the diagram stays', /getContext\('webgl2'\) \|\| c\.getContext\('webgl'\)/.test(js) && /if \(!ok && btn\) btn\.hidden = true/.test(js));
  const used = [...new Set([...js.matchAll(/\bT\.([A-Z][A-Za-z0-9_]*)/g)].map((m) => m[1]))];
  const vendor = await import(pathToFileURL(path.join(ROOT, 'docs/assets/js/vendor/three-roof.min.js')).href);
  const missing = used.filter((n) => !(n in vendor));
  ok('the trimmed Three.js exports everything roof-3d.js uses (else: node scripts/build-three-roof.mjs)', missing.length === 0, 'missing: ' + missing.join(', '));
  ok('Three.js license ships alongside', /The MIT License/.test(read('docs/assets/js/vendor/three-LICENSE.txt')));

  console.log('\n' + passed + ' passed, ' + failed + ' failed');
  if (failed) { console.log('FAILED: ' + fails.join(' | ')); process.exit(1); }
})().catch((e) => { console.error(e); process.exit(1); });
